# lib/recipes.sh -- fetches github.com/Qsenja/fau-recipes over plain HTTPS
# raw-content requests, no `git` involved. Requires lib/common.sh already
# sourced. See fau.md.
#
# Two-tier, index-then-file, not a whole-repo tarball pull: recipes.db (a
# plain-text list of every recipe name, one per line, regenerated by that
# repo's own update-index.sh) is small and fetched every time; an individual
# recipes/<name>.fis is fetched lazily, only for a name actually requested --
# this stays cheap no matter how large the recipes collection grows, unlike
# downloading the entire repo just to build one package. Re-fetched fresh on
# every lookup, same as recipes.db itself -- see recipe_lookup's own comment
# for why an earlier "fetch once, trust the cached copy forever" version of
# this was a real bug, not just an optimization.

recipes_raw_base() {
	echo "${FAU_RECIPES_REPO/github.com/raw.githubusercontent.com}/${FAU_RECIPES_BRANCH}"
}

# Best-effort: a fetch failure is logged and swallowed (return 1), never
# die()'d -- callers need to keep working offline off of whatever's already
# cached, or the ISO-shipped FAU_RECIPES_DIR fallback, not hard-fail a
# build/update just because the network happened to be down at that exact
# moment. Setting FAU_RECIPES_REPO="" explicitly (as opposed to leaving it
# unset, which takes the real default) skips the network call entirely --
# for anyone who wants fully offline, shipped-recipes-only behavior on
# purpose.
recipes_sync() {
	[ -n "${FAU_RECIPES_REPO:-}" ] || return 0
	local base; base=$(recipes_raw_base)
	local tmp; tmp=$(mktemp)
	if ! curl -sL --fail -o "$tmp" "$base/recipes.db" 2>/dev/null; then
		rm -f "$tmp"
		log "warning: couldn't fetch the recipes index from $FAU_RECIPES_REPO (offline?) -- using whatever's already cached/shipped"
		return 1
	fi
	mkdir -p "$FAU_RECIPES_REMOTE_DIR"
	mv "$tmp" "$FAU_RECIPES_REMOTE_DIR/recipes.db"
	return 0
}

# The remote index wins over the read-only ISO-shipped fallback when both
# know a same-named recipe -- see fau.md. A name present in the synced
# recipes.db gets its .fis (re-)fetched fresh on every single lookup, not
# just the first one -- a fetch failure here falls back to whatever was
# cached from the last successful fetch (offline resilience, same "never
# worse than before" shape as recipes_sync itself), or the shipped copy if
# there's no cached one either, but never SKIPS the fetch attempt just
# because a copy happens to already exist locally.
#
# A real, live bug this fixes, not a hypothetical: this used to check
# `[ ! -f "$cached" ]` and skip the fetch entirely the moment any copy
# already existed, trusting whatever it downloaded the very first time as
# permanently correct forever after. That directly fights this whole
# system's own stated purpose ("so a new recipe reaches every
# FloraOS machine as soon as it's pushed here, without needing a new ISO")
# -- a machine that ran `fau build <name>` once, before a recipe bug was
# fixed and pushed, would NEVER see that fix, no matter how many more
# times `fau update`/`fau build <name>` ran afterward. Found for real: a
# live FloraOS box that had already fetched a broken cursor.fis (before a
# real `PKG_DEPENDS` bug in it was fixed and pushed to fau-recipes) kept
# failing with the exact same already-fixed error on every retry, because
# nothing ever re-checked GitHub for that one file again -- only deleting
# the cached copy by hand made the fix visible. Worse, `fau update`'s own
# "third kind" version check (see fau.md) reads `PKG_VERSION` straight out
# of this same cached file for every build-installed package, on every
# single `fau update` call -- so this bug meant `fau update` could report
# "up to date" forever off a stale recipe too, not just `fau build`.
recipe_lookup() {
	local name=$1
	local index="$FAU_RECIPES_REMOTE_DIR/recipes.db"
	if [ -f "$index" ] && grep -qxF "$name" "$index"; then
		local cached="$FAU_RECIPES_REMOTE_DIR/recipes/$name.fis"
		mkdir -p "$FAU_RECIPES_REMOTE_DIR/recipes"
		local base; base=$(recipes_raw_base)
		if curl -sL --fail -o "$cached.part" "$base/recipes/$name.fis" 2>/dev/null; then
			mv "$cached.part" "$cached"
		else
			rm -f "$cached.part"
			if [ -f "$cached" ]; then
				log "warning: fetching recipes/$name.fis from $FAU_RECIPES_REPO failed -- using the last successfully fetched copy (offline?)"
			else
				log "warning: '$name' is in the recipes index but fetching recipes/$name.fis from $FAU_RECIPES_REPO failed -- falling back to the shipped copy if there is one"
			fi
		fi
		[ -f "$cached" ] && { echo "$cached"; return 0; }
	fi
	if [ -f "$FAU_RECIPES_DIR/$name.fis" ]; then
		echo "$FAU_RECIPES_DIR/$name.fis"
	else
		return 1
	fi
}

recipe_list_names() {
	# Neither the index nor the shipped dir existing is a normal, common
	# state (e.g. before any sync has ever succeeded), not a failure --
	# trailing `true` so that doesn't make the last command in this group
	# exit non-zero, which under `set -o pipefail` would otherwise propagate
	# out of the whole pipeline and this function even though the listing
	# itself is correct (see fau.md -- this exact bug shipped once already).
	{
		[ -f "$FAU_RECIPES_REMOTE_DIR/recipes.db" ] && cat "$FAU_RECIPES_REMOTE_DIR/recipes.db"
		[ -d "$FAU_RECIPES_DIR" ] && find "$FAU_RECIPES_DIR" -maxdepth 1 -name '*.fis' -printf '%f\n' 2>/dev/null | sed 's/\.fis$//'
		true
	} | sort -u
}
