# lib/recipes.sh -- fetches github.com/Qsenja/fau-recipes over plain HTTPS
# raw-content requests, no `git` involved. Requires lib/common.sh already
# sourced. See fau.md.
#
# Two-tier, index-then-file, not a whole-repo tarball pull: <db>.db (a
# plain-text list of every recipe name, one per line, regenerated by that
# repo's own update-index.sh) is small and fetched every time; an individual
# <subdir>/<name>.fis is fetched lazily, only for a name actually requested --
# this stays cheap no matter how large the recipes collection grows, unlike
# downloading the entire repo just to build one package. Re-fetched fresh on
# every lookup, same as the index itself -- see fau.md.
#
# Parametrized over (repo, branch, remote-dir, db-name, subdir, shipped-dir)
# so the same fetch/fallback logic serves two namespaces in the same repo:
# app recipes (recipes.db/recipes/, the original, ISO-shipped-fallback-
# capable shape) and system recipes (system-recipes.db/system/, used by
# `fau bootstrap-build` -- no shipped fallback, purely a live-update
# feature). See fau.md's "fau update also sweeps base system packages"
# section for why the two are kept apart.

_recipes_raw_base() {
	local repo=$1 branch=$2
	echo "${repo/github.com/raw.githubusercontent.com}/${branch}"
}

# Best-effort: a fetch failure is logged and swallowed (return 1), never
# die()'d -- callers need to keep working offline off of whatever's already
# cached, or the ISO-shipped fallback dir, not hard-fail a build/update just
# because the network happened to be down at that exact moment. An empty
# repo (as opposed to unset, which takes the real default) skips the network
# call entirely -- for anyone who wants fully offline, shipped-recipes-only
# behavior on purpose.
_recipes_sync() {
	local repo=$1 branch=$2 remote_dir=$3 db_name=$4 label=$5
	[ -n "$repo" ] || return 0
	local base; base=$(_recipes_raw_base "$repo" "$branch")
	local tmp; tmp=$(mktemp)
	log "fetching $label..."
	if ! curl -sL --fail -o "$tmp" "$base/$db_name" 2>/dev/null; then
		rm -f "$tmp"
		log "warning: couldn't fetch the $label from $repo (offline?) -- using whatever's already cached/shipped"
		return 1
	fi
	mkdir -p "$remote_dir"
	mv "$tmp" "$remote_dir/$db_name"
	return 0
}

# The remote index wins over the read-only ISO-shipped fallback (if any --
# system recipes have none) when both know a same-named recipe. A name
# present in the synced db gets its .fis (re-)fetched fresh on every lookup,
# falling back to the last successfully fetched copy (or the shipped one)
# only if the network call fails -- see fau.md.
_recipe_lookup() {
	local name=$1 repo=$2 branch=$3 remote_dir=$4 db_name=$5 subdir=$6 shipped_dir=$7
	local index="$remote_dir/$db_name"
	if [ -f "$index" ] && grep -qxF "$name" "$index"; then
		local cached="$remote_dir/$subdir/$name.fis"
		mkdir -p "$remote_dir/$subdir"
		local base; base=$(_recipes_raw_base "$repo" "$branch")
		if curl -sL --fail -o "$cached.part" "$base/$subdir/$name.fis" 2>/dev/null; then
			mv "$cached.part" "$cached"
		else
			rm -f "$cached.part"
			if [ -f "$cached" ]; then
				log "warning: fetching $subdir/$name.fis from $repo failed -- using the last successfully fetched copy (offline?)"
			else
				log "warning: '$name' is in the recipes index but fetching $subdir/$name.fis from $repo failed -- falling back to the shipped copy if there is one"
			fi
		fi
		[ -f "$cached" ] && { echo "$cached"; return 0; }
	fi
	if [ -n "$shipped_dir" ] && [ -f "$shipped_dir/$name.fis" ]; then
		echo "$shipped_dir/$name.fis"
	else
		return 1
	fi
}

_recipe_list_names() {
	local remote_dir=$1 db_name=$2 shipped_dir=$3
	# Neither the index nor the shipped dir existing is a normal, common
	# state (e.g. before any sync has ever succeeded), not a failure --
	# trailing `true` so that doesn't make the last command in this group
	# exit non-zero, which under `set -o pipefail` would otherwise propagate
	# out of the whole pipeline and this function even though the listing
	# itself is correct (see fau.md -- this exact bug shipped once already).
	{
		[ -f "$remote_dir/$db_name" ] && cat "$remote_dir/$db_name"
		[ -n "$shipped_dir" ] && [ -d "$shipped_dir" ] && find "$shipped_dir" -maxdepth 1 -name '*.fis' -printf '%f\n' 2>/dev/null | sed 's/\.fis$//'
		true
	} | sort -u
}

# Public wrappers -- app recipes (unchanged behavior/signature).
recipes_raw_base() { _recipes_raw_base "$FAU_RECIPES_REPO" "$FAU_RECIPES_BRANCH"; }
recipes_sync() { _recipes_sync "${FAU_RECIPES_REPO:-}" "$FAU_RECIPES_BRANCH" "$FAU_RECIPES_REMOTE_DIR" "recipes.db" "recipes databank (official fis index)"; }
recipe_lookup() { _recipe_lookup "$1" "${FAU_RECIPES_REPO:-}" "$FAU_RECIPES_BRANCH" "$FAU_RECIPES_REMOTE_DIR" "recipes.db" "recipes" "$FAU_RECIPES_DIR"; }
recipe_list_names() { _recipe_list_names "$FAU_RECIPES_REMOTE_DIR" "recipes.db" "$FAU_RECIPES_DIR"; }

# Public wrappers -- system recipes: same repo, separate index/subdir, no
# shipped fallback (see fau.md).
system_recipes_sync() { _recipes_sync "${FAU_RECIPES_REPO:-}" "$FAU_RECIPES_BRANCH" "$FAU_SYSTEM_RECIPES_REMOTE_DIR" "system-recipes.db" "system recipes databank"; }
system_recipe_lookup() { _recipe_lookup "$1" "${FAU_RECIPES_REPO:-}" "$FAU_RECIPES_BRANCH" "$FAU_SYSTEM_RECIPES_REMOTE_DIR" "system-recipes.db" "system" ""; }
system_recipe_list_names() { _recipe_list_names "$FAU_SYSTEM_RECIPES_REMOTE_DIR" "system-recipes.db" ""; }
